# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/parallel-motion-detection

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/parallel-motion-detection

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/parallel-motion-detection/CMakeFiles /workspaces/parallel-motion-detection//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/parallel-motion-detection/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FrameTa

# Build rule for target.
FrameTa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FrameTa
.PHONY : FrameTa

# fast build rule for target.
FrameTa/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FrameTa.dir/build.make CMakeFiles/FrameTa.dir/build
.PHONY : FrameTa/fast

#=============================================================================
# Target rules for targets named BlackWhite

# Build rule for target.
BlackWhite: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BlackWhite
.PHONY : BlackWhite

# fast build rule for target.
BlackWhite/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackWhite.dir/build.make CMakeFiles/BlackWhite.dir/build
.PHONY : BlackWhite/fast

#=============================================================================
# Target rules for targets named Conv

# Build rule for target.
Conv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Conv
.PHONY : Conv

# fast build rule for target.
Conv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Conv.dir/build.make CMakeFiles/Conv.dir/build
.PHONY : Conv/fast

experiments/BlackWhite.o: experiments/BlackWhite.cpp.o
.PHONY : experiments/BlackWhite.o

# target to build an object file
experiments/BlackWhite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackWhite.dir/build.make CMakeFiles/BlackWhite.dir/experiments/BlackWhite.cpp.o
.PHONY : experiments/BlackWhite.cpp.o

experiments/BlackWhite.i: experiments/BlackWhite.cpp.i
.PHONY : experiments/BlackWhite.i

# target to preprocess a source file
experiments/BlackWhite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackWhite.dir/build.make CMakeFiles/BlackWhite.dir/experiments/BlackWhite.cpp.i
.PHONY : experiments/BlackWhite.cpp.i

experiments/BlackWhite.s: experiments/BlackWhite.cpp.s
.PHONY : experiments/BlackWhite.s

# target to generate assembly for a file
experiments/BlackWhite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackWhite.dir/build.make CMakeFiles/BlackWhite.dir/experiments/BlackWhite.cpp.s
.PHONY : experiments/BlackWhite.cpp.s

experiments/Conv.o: experiments/Conv.cpp.o
.PHONY : experiments/Conv.o

# target to build an object file
experiments/Conv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Conv.dir/build.make CMakeFiles/Conv.dir/experiments/Conv.cpp.o
.PHONY : experiments/Conv.cpp.o

experiments/Conv.i: experiments/Conv.cpp.i
.PHONY : experiments/Conv.i

# target to preprocess a source file
experiments/Conv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Conv.dir/build.make CMakeFiles/Conv.dir/experiments/Conv.cpp.i
.PHONY : experiments/Conv.cpp.i

experiments/Conv.s: experiments/Conv.cpp.s
.PHONY : experiments/Conv.s

# target to generate assembly for a file
experiments/Conv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Conv.dir/build.make CMakeFiles/Conv.dir/experiments/Conv.cpp.s
.PHONY : experiments/Conv.cpp.s

experiments/FrameTa.o: experiments/FrameTa.cpp.o
.PHONY : experiments/FrameTa.o

# target to build an object file
experiments/FrameTa.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FrameTa.dir/build.make CMakeFiles/FrameTa.dir/experiments/FrameTa.cpp.o
.PHONY : experiments/FrameTa.cpp.o

experiments/FrameTa.i: experiments/FrameTa.cpp.i
.PHONY : experiments/FrameTa.i

# target to preprocess a source file
experiments/FrameTa.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FrameTa.dir/build.make CMakeFiles/FrameTa.dir/experiments/FrameTa.cpp.i
.PHONY : experiments/FrameTa.cpp.i

experiments/FrameTa.s: experiments/FrameTa.cpp.s
.PHONY : experiments/FrameTa.s

# target to generate assembly for a file
experiments/FrameTa.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FrameTa.dir/build.make CMakeFiles/FrameTa.dir/experiments/FrameTa.cpp.s
.PHONY : experiments/FrameTa.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BlackWhite"
	@echo "... Conv"
	@echo "... FrameTa"
	@echo "... experiments/BlackWhite.o"
	@echo "... experiments/BlackWhite.i"
	@echo "... experiments/BlackWhite.s"
	@echo "... experiments/Conv.o"
	@echo "... experiments/Conv.i"
	@echo "... experiments/Conv.s"
	@echo "... experiments/FrameTa.o"
	@echo "... experiments/FrameTa.i"
	@echo "... experiments/FrameTa.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

